---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s.startkubernetes.com.my.domain
  resources:
  - pdfdocuments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.startkubernetes.com.my.domain
  resources:
  - pdfdocuments/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.startkubernetes.com.my.domain
  resources:
  - pdfdocuments/status
  verbs:
  - get
  - patch
  - update
